# Generated by Django 4.2.5 on 2023-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Chat ID'),
        ),
    ]
