# Generated by Django 4.2.5 on 2023-10-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
    ]
