# Generated by Django 4.2.5 on 2023-10-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=255,
                    verbose_name='Название действия'
                )),
            ],
        ),
        migrations.CreateModel(
            name='LinkedHabit',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('description', models.TextField(
                    verbose_name='Описание связанной привычки'
                )),
                ('is_pleasurable', models.BooleanField(
                    default=True,
                    verbose_name='статус'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=255,
                    verbose_name='Название места'
                )),
            ],
        ),
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('description', models.TextField(
                    verbose_name='Описание приятной привычки'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('time', models.TimeField(
                    blank=True, null=True,
                    verbose_name='Время выполнения')),
                ('frequency', models.PositiveIntegerField(
                    default=1, verbose_name='Частота')),
                ('estimated_time', models.PositiveIntegerField(
                    verbose_name='Оцененное время выполнения')),
                ('is_public', models.BooleanField(
                    default=False, verbose_name='Публичность')),
                ('is_completed', models.BooleanField(
                    default=False, verbose_name='Завершено')),
                ('last_completed', models.DateTimeField(
                    blank=True, null=True,
                    verbose_name='Последнее выполнение')),
                ('action', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='habits.action', verbose_name='Действие')),
                ('linked_habit', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='habits.linkedhabit',
                    verbose_name='Связанная привычка')),
                ('place', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='habits.place', verbose_name='Место')),
                ('pleasant_habit', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='habits.pleasanthabit',
                    verbose_name='Приятная привычка')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь')),
            ],
        ),
    ]
